apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  labels:
    app: metabase
data:
  MB_DB_TYPE: "postgres"
  MB_DB_DBNAME: "postgres"
  MB_DB_PORT: "5432"
  MB_DB_USER: "postgres"
  MB_DB_PASS: "postgres"
  MB_DB_HOST: "10.7.49.182" #Incluir o ip do services do postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: metabase
  template:
    metadata:
      labels:
        deploy: metabase
        app: metabase
    spec:
      restartPolicy: Always
      containers:
        - name: metabase
          imagePullPolicy: IfNotPresent
          image: metabase/metabase:v0.35.3
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: metabase-config
