apiVersion: v1
kind: Service
metadata:
    labels:
	app: metabase
    name: metabase-svc
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      protocol: TCP
      name: http
    selector:
	app: metabase