apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: metabase-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metabase
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 100
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
