apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  labels:
    app: metabase
data:
  MB_DB_TYPE: "postgres"
  MB_DB_DBNAME: "postgres"
  MB_DB_PORT: "31941"
  MB_DB_USER: "postgres"
  MB_DB_PASS: "postgres"
  MB_DB_HOST: "192.168.1.10" #inser ir ipprivado da rede aqui

---

apiVersion: v1
kind: Service
metadata:
    labels:
        app: metabase
    name: metabase-svc
spec:
    type: LoadBalancer
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      name: http
    selector:
        app: metabase

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: metabase
  template:
    metadata:
      labels:
        deploy: metabase
        app: metabase
    spec:
      restartPolicy: Always
      containers:
        - name: metabase
          imagePullPolicy: IfNotPresent
          image: metabase/metabase:v0.35.3
          resources:
            requests:
              cpu: 500m
          ports:
          - containerPort: 3000
          envFrom:
            - configMapRef:
                name: metabase-config

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: metabase-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metabase
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 100
  #behavior:
    #scaleUp:
      #stabilizationWindowSeconds: 300
