apiVersion: v1
kind: Service
metadata:
  name: metabase-svc
spec:
  type: LoadBalancer
  selector:
    app: metabase
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
