apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      name: postgres
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-db
  
